#! /bin/bash
BIN="$(echo $HOME)/.local/bin/"
CURRENT_DIR="$(pwd)"
DMENU_BIN="$CURRENT_DIR/dmenu/bin/"

for script in $CURRENT_DIR/bin/*; do
				ln -sf $script $BIN
done

for script in $CURRENT_DIR/dmenu/bin/*; do 
				ln -sf $script $BIN
done


